### ISSUE TITLE
Socket.io is throwing a 404 while attempting to long poll from the same URL as the game locally

### ISSUE THREAD

**Issue by mrispoli24** [IgnasKavaliauskas/SocketIO-GMS2-Extension#11]
After following the instructions we're seeing errors with the socket appearing to long poll. Our server is getting the initial connection but cannot seem to figure out why this is happening in the example code.

<img width="1338" alt="image" src="https://user-images.githubusercontent.com/5890462/158892278-a2e5ce12-6f50-42a9-b6b3-a116d0b35986.png">

**Comment by ignoxx** [comment]
@mrispoli24 can you test if @rhea-so fix solved it?

**Comment by jeonghyeon-net** [comment]
> @mrispoli24 can you test if @rhea-so fix solved it?

I tried and it solved.

I want to upload the screenshot, but I don't know how to open developer tools.

I guess GameMaker Studio 2 is interrupt keyboard input.

**Comment by ignoxx** [comment]
Great. You can still do that by clicking inside of the url bar and pressing (F12 or F11?)
