### ISSUE TITLE
Upgrade socket.io to latest version

### ISSUE THREAD

**Issue by ignoxx** [IgnasKavaliauskas/SocketIO-GMS2-Extension#13]
The latest version of socket.io is (as of today) `v4.4.1`. To keep the extension up to date, we would require to update the `socket.io.js ` file in `Source/`

## Steps
1. Get the latest `socket.io.min.js` from [here](https://github.com/socketio/socket.io/tree/main/client-dist)
2. Rename it to `socket.io.js`
3. Replace it with the old one in `Source/socket.io.js`
4. **TEST** that everything is still working for all example projects!
5. (optionally) create the extension file (.yymps) within the GameMaker IDE and create a new release / or just attach it here and I'll take care of it

Sadly I don't have time to do it by myself, any help is appreciated

**Comment by PureNukage** [comment]
I had a GM project connect to my node server successfully, no errors. And then a bit later I was getting errors with (afaik) no changes to any code. 
The error message is `Unhandled Exception - Uncaught ReferenceError: gml_Script_gmcallback_sio_on_connect is not defined in file http://localhost:51264/html5game/tph_gms2.api.js at line 33`

When I go to this URL that function is definitely in there (however my GM is empty of any socket.io related scripts, only the Extension exists) 

Is this related to the v4.4.1 upgrade and the gms2.api being out of date? Am I missing the GM script-resource? 

Appreciate any help and I'm willing to help in any way I can.

**Comment by ignoxx** [comment]
builds are automated now
