### ISSUE TITLE
Unhandled Exception - Uncaught ReferenceError: gml_Script_gmcallback_sio_on_connect is not defined in file http://localhost:51264/html5game/tph_gms2.api.js at line 33

### ISSUE THREAD

**Issue by PureNukage** [IgnasKavaliauskas/SocketIO-GMS2-Extension#14]
I had a GM project connect to my node server successfully, no errors. And then a bit later I was getting errors with (afaik) no changes to any code.
The error message is Unhandled Exception - Uncaught ReferenceError: gml_Script_gmcallback_sio_on_connect is not defined in file http://localhost:51264/html5game/tph_gms2.api.js at line 33

When I go to this URL that function is definitely in there (however my GM is empty of any socket.io related scripts, only the Extension exists)

Is this related to the v4.4.1 upgrade and the gms2.api being out of date? Am I missing the GM script-resource?

Appreciate any help and I'm willing to help in any way I can.

**Comment by PureNukage** [comment]
Silly of me to have opened this as an issue. It's more an issue with the Extension as it exists on the YoYo Marketplace, where the gml_callback functions aren't included.

**Comment by ignoxx** [comment]
socket.io v4 contains some API breaking changes, maybe that's the issue here, I haven't tested it tho. Have you tried using the latest v3?
