### ISSUE TITLE
connected to server! but cant see any players

### ISSUE THREAD

**Issue by ghost** [IgnasKavaliauskas/SocketIO-GMS2-Extension#7]
connected to server! but cant see any players, created server on node and trying to just run your example1
![Adsız](https://user-images.githubusercontent.com/33418107/78725045-50900780-7937-11ea-99f7-29f8c07a7e4c.png)

**Comment by ignoxx** [comment]
Someone reported the same issue today as well, I’ll try to take a look on it this evening.

Did you tried a different browser?

**Comment by ignoxx** [comment]
@durancanyilmaz Someone told me that restarting his PC has fixed this issue, did you tried it already?

**Comment by ignoxx** [comment]
I've just tested the Example1 with the latest versions of GMS2 (v2.2.5.378) and node (v8.10.0) and everything is working as expected. 

Did you get it working?

**Comment by ghost** [comment]
still not creating oPlayer with different browser and im using same version gms2, i will check node version now
![Adsız](https://user-images.githubusercontent.com/33418107/79068970-512bf380-7cd3-11ea-8b39-5a8e327571e9.png)

**Comment by ghost** [comment]
my node version is v10.16.0

**Comment by ghost** [comment]
Your create_player event is want x,y,id,username data but server is not sending. Im trying to send from server to client this data now.
edit: yes!
with this server code creating player

```
//when created player
 client.on('create_player', (data) => {
    data=JSON.parse(data);
        console.log(`username: > '${data.username}'`);
        //send same data back
        client.emit("create_player", {
          x:0,
          y:0,
          id:client.id,
          username:data.username
        });
    });
```

**Comment by ignoxx** [comment]
So you got it working now?

**Comment by ghost** [comment]
yes its working now
