### ISSUE TITLE
HTTPS and SSL

### ISSUE THREAD

**Issue by ItsDedSec00** [IgnasKavaliauskas/SocketIO-GMS2-Extension#8]
Unfortunately the game does not connect after uploading to a hoster. After searching Google I found the error that Socket IO cannot connect with SSL or HTTPS. I have found some solutions on the web but I don't know enough about connecting to Game Maker to change this. Can you help me with that?

**Comment by ItsDedSec00** [comment]
I changed the server script so that it works on HTTPS sites, but as soon as I upload it to my webhoster it does not work anymore. How did you do that? Or can't you upload it at all? Which of course would be pointless.

**Comment by ignoxx** [comment]
Hi,

your link also says that it's enough to just write "http*s*://....." to
enable the secure mode. But you should be able to just use http too.

Make sure your client has the right address to your server and that your
server is reachable in public. If you host it on your PC, make sure to open
the right ports in your router/pc.
